export const Actions = {
  MOVIES_LOADING: "MOVIES_LOADING",
  MOVIES_SUCCES: "MOVIES_SUCCES",
  MOVIES_ERROR: "MOVIES_ERROR",

  GENRES_LOADING: "GENRES_LOADING",
  GENRES_SUCCES: "GENRES_SUCCES",
  GENRES_ERROR: "GENRES_ERROR",
};

export default Actions;
